### ISSUE TITLE
[Issue 2] Homepage Layout

### ISSUE THREAD

**Issue by nevanscott** [midnightbreakfast/web#109]
This goes here:

https://github.com/midnightbreakfast/web/blob/magazine/_src/_data/issues.yml

You'll see something like this:

``` yaml
issue2:
  number: 2
  contents:
    - sample
  letter: /issue-2-letter/
```

Replace "sample" with whatever url slugs you set for the issues.

Let me know if you have any questions, I just wanted to get this started. If I need to do it, I can take care of it.
